import {
  Cpu,
  Smartphone,
  Tv2,
  Gamepad2,
  Headphones,
  Search,
  Filter,
  ArrowUpDown,
  Trash2,
  Bell,
  Sparkles,
  ChevronDown,
  ChevronRight,
  X,
  Star,
  DollarSign,
  TrendingUp,
} from 'lucide-react';

export const Icons = {
  logo: Cpu,
  smartphone: Smartphone,
  tv: Tv2,
  console: Gamepad2,
  audio: Headphones,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  delete: Trash2,
  alert: Bell,
  sparkles: Sparkles,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  star: Star,
  dollar: DollarSign,
  trendingUp: TrendingUp,
};
